import '../theme/app_icons.dart';
import 'package:flutter/material.dart';

/// User guide content.
///
/// Ported from the Expo app's guide, which was written against the live app and re-checked
/// screen by screen, plus an Auto Pay page this app added.
///
/// The Expo guide's screenshots were NOT carried over — they are pictures of the Expo UI.
/// [GuideStep.shot] instead names a capture of THIS app's screen, generated by
/// tool/capture_guide_shots.dart from seeded, entirely fictional data. Only pages whose screen
/// renders fully without the network have one; the rest are text-and-steps, because a
/// picture of an empty loading state teaches a reader nothing.
///
/// No API calls anywhere in the guide: it has to work before the member has signed in.
class GuideStep {
  final String key;
  final IconData icon;
  final String title;
  final String intro;
  final List<GuideDetail> details;
  final List<String> tips;

  /// Highlighted "read this or you will get it wrong" callout.
  final String note;

  /// Asset path of a screenshot of this app, or '' when the page has none.
  final String shot;

  const GuideStep({
    required this.key,
    required this.icon,
    required this.title,
    required this.intro,
    required this.details,
    this.tips = const [],
    this.note = '',
    this.shot = '',
  });
}

class GuideDetail {
  final int n;
  final String title;
  final String text;
  const GuideDetail(this.n, this.title, this.text);
}

const kGuideSteps = <GuideStep>[
  GuideStep(
    key: 'signin',
    shot: 'assets/guide/login.png',
    icon: Icons.login,
    title: 'Signing in',
    intro:
        'Your academy issues one account per member. Everything you see in the app — fees, attendance, grading — belongs to that account.',
    details: [
      GuideDetail(1, 'Student or Instructor',
          'Students stay on the Student tab. Instructors switch to Instructor, which also asks for a club code and branch — those come from your academy.'),
      GuideDetail(2, 'Student ID, phone or email',
          'Any one of the three works. If you are not sure what your student ID is, your academy can look it up for you.'),
      GuideDetail(3, 'Password',
          'Tap the eye to check what you typed. Forgot? sends a reset request to your academy — they confirm your identity before issuing a new one.'),
      GuideDetail(4, 'You stay signed in',
          'After one successful sign-in the app remembers this device, so you go straight to your dashboard next time. Logging out from Profile clears it.'),
    ],
    tips: [
      'Not a member yet? Contact your academy at the bottom of this screen — accounts are created by the club, not in the app.',
      'This guide is on the sign-in screen too, so you can read it before you have an account.',
    ],
  ),
  GuideStep(
    key: 'home',
    shot: 'assets/guide/home.png',
    icon: AppIcons.home,
    title: 'Your home dashboard',
    intro:
        'Home is the summary of everything that needs your attention today. It refreshes from the club system each time you open it.',
    details: [
      GuideDetail(1, 'Your three headline numbers',
          'Open invoices, your current grade and total amount due. Tapping the card takes you to the detail behind it.'),
      GuideDetail(2, 'Shortcut row',
          'Training, Attendance, Timetable, Virtual ID and Profile — the five things members open most, one tap from the top of the screen.'),
      GuideDetail(3, 'Fees due',
          'Pay Now opens the payment screen with your outstanding invoices already listed. The card disappears when you owe nothing.'),
      GuideDetail(4, 'Today\'s class',
          'Your next session with its time, centre and instructor. Check In jumps straight to the QR scanner.'),
      GuideDetail(5, 'Quick Access + the bell',
          'Shortcuts to every feature, ending in More for the full catalogue. The bell badge counts unread club notifications.'),
    ],
  ),
  GuideStep(
    key: 'checkin',
    shot: 'assets/guide/attendance.png',
    icon: AppIcons.qr_code_scanner,
    title: 'Checking in with QR',
    intro:
        'Attendance is marked by scanning the QR poster displayed at your training centre. Tap Scan — the round button in the middle of the tab bar — and point your camera at it.',
    details: [
      GuideDetail(1, 'Your attendance rate',
          'Present, absent and total sessions. Clubs commonly ask for 80% or better before you can enter gradings and events.'),
      GuideDetail(2, 'Scan QR to Check In',
          'Opens the camera. Allow camera access the first time. Hold steady until the code is recognised — you get a clear success or failure message on the spot.'),
      GuideDetail(3, 'If you are asked to pick a class',
          'When a centre runs more than one session at that hour, the app asks which class you are attending. Choose it and the check-in completes.'),
      GuideDetail(4, 'Recent attendance',
          'Every check-in the club has recorded, newest first, with a separate list of classes you missed.'),
    ],
    tips: [
      'Nothing recorded? Check with the front desk that you scanned the current poster — centres reprint them when details change.',
    ],
    note:
        'Scan the centre\'s poster, not your own Virtual ID. The centre code says WHERE you are training; your personal QR is only for identifying yourself at the counter and will be rejected by the check-in scanner.',
  ),
  GuideStep(
    key: 'schedule',
    shot: 'assets/guide/schedule.png',
    icon: AppIcons.calendar_month,
    title: 'Your timetable',
    intro:
        'Schedule shows the training week for the centres you belong to, so you can see at a glance which days you train.',
    details: [
      GuideDetail(1, 'The week strip',
          'Tap any day to load its sessions. The highlighted day is the one you are viewing.'),
      GuideDetail(2, 'Session cards',
          'Start and end time, the training centre, your instructor and the grade the session is aimed at.'),
      GuideDetail(3, 'Rest days are normal',
          'A day with no sessions shows Rest Day rather than an empty screen — recovery is part of the programme.'),
      GuideDetail(4, 'Book a class',
          'The button in the corner opens booking, covered on the next page.'),
    ],
  ),
  GuideStep(
    key: 'booking',
    shot: 'assets/guide/book-class.png',
    icon: AppIcons.event_available,
    title: 'Booking a class',
    intro:
        'Booking reserves your place in a session. Work down the screen: centre, then instructor, then month, then the session itself.',
    details: [
      GuideDetail(1, 'Training centre and instructor',
          'Only the centres and instructors you are registered with appear. Changing either reloads the sessions below.'),
      GuideDetail(2, 'Month',
          'Switches which month you are booking into, so you can reserve ahead.'),
      GuideDetail(3, 'Available sessions',
          'Each row is a weekday slot with its time, centre and instructor. Select one, then pick the exact date it runs on.'),
      GuideDetail(4, 'My Bookings',
          'Everything you have reserved, with its status. The app blocks you from booking the same class twice on the same date.'),
    ],
    tips: [
      'Booked by mistake, or plans changed? Tell your academy — cancellations are handled by the club, not in the app.',
    ],
  ),
  GuideStep(
    key: 'payments',
    shot: 'assets/guide/payments.png',
    icon: AppIcons.account_balance_wallet,
    title: 'Fees and payments',
    intro:
        'Everything financial lives under Payments: what you owe now, months you want to settle early, and every receipt you have ever been issued.',
    details: [
      GuideDetail(1, 'Three tabs',
          'Pay is what is outstanding today. Advance Payment settles future months before they are invoiced. History is every past payment and receipt.'),
      GuideDetail(2, 'Who you are paying for',
          'If your family has more than one member at the academy, the name chips let you switch between them and pay each one\'s fees.'),
      GuideDetail(3, 'Pick your invoices',
          'Tick one or several — the running total updates as you go — then tap Pay to open the payment sheet.'),
      GuideDetail(4, 'How you pay',
          'Online card / FPX / e-wallet through the club\'s secure gateway, or Direct Bank-In, where you transfer manually and attach a photo of the slip from your gallery or camera.'),
      GuideDetail(5, 'Receipts',
          'Any receipt in History can be downloaded as an official PDF. There is no automatic monthly payment: every payment is one you make yourself.'),
    ],
    note:
        'A Direct Bank-In payment is not settled the moment you upload the slip — your academy reviews it first, and the invoice stays pending until they approve it.',
  ),
  GuideStep(
    key: 'autopay',
    shot: 'assets/guide/autopay.png',
    icon: AppIcons.autorenew,
    title: 'Auto Pay reminders',
    intro:
        'Auto Pay is a monthly nudge, not a direct debit. It reminds you when fees are due and opens the payment with the right months already ticked.',
    details: [
      GuideDetail(1, 'Turn it on',
          'One switch. Your phone will ask permission to show notifications the first time — without that the reminder cannot appear, and the screen will tell you so.'),
      GuideDetail(2, 'Pick the day',
          'Any day from the 1st to the 28th. It stops at 28 on purpose so your reminder never lands on a date February does not have.'),
      GuideDetail(3, 'Choose how far ahead',
          'Settle one month at a time, or up to six at once. The current month is not included — it is already invoiced and shows under Fees Due.'),
      GuideDetail(4, 'When the reminder arrives',
          'Tap it and the payment screen opens with those months selected. Check the amount, then pay as normal.'),
    ],
    tips: [
      'Reminders stop the moment you switch Auto Pay off. Nothing is left running in the background.',
      'If your phone misses the reminder — after a restart, say — D-CLIX prompts you the next time you open the app.',
    ],
    note:
        'Your money is never taken automatically. The club system cannot hold a direct debit or keep your card on file, so every payment still needs you to tap Pay. Do not treat Auto Pay as proof your fees are settled — check Fees Due.',
  ),
  GuideStep(
    key: 'notifications',
    shot: 'assets/guide/notifications.png',
    icon: AppIcons.notifications,
    title: 'Notifications',
    intro:
        'Fee reminders, class changes and club announcements all arrive here, and as alerts on your phone.',
    details: [
      GuideDetail(1, 'Unread first',
          'Unread messages are highlighted and counted on the home bell. Tap one to expand the full text — that also marks it read.'),
      GuideDetail(2, 'Mark all read',
          'The double-tick in the header clears the badge in one go.'),
      GuideDetail(3, 'Settings',
          'The sliders icon opens alert settings — sound, categories and quiet hours. That is the next page.'),
      GuideDetail(4, 'How often it checks',
          'While the app is open it looks for new messages every minute. Closed, your phone checks roughly every 15 minutes in the background.'),
    ],
  ),
  GuideStep(
    key: 'alerts',
    shot: 'assets/guide/notification-settings.png',
    icon: Icons.tune,
    title: 'Alert settings',
    intro:
        'Control exactly how your phone behaves when the club sends something. Every option here is per-device, so your phone and your tablet can differ.',
    details: [
      GuideDetail(1, 'Sound and vibration',
          'Turn the D-CLIX chime on or off, and whether alerts buzz. Turning both off still delivers the message silently to your tray.'),
      GuideDetail(2, 'Send a test notification',
          'Fires a sample alert immediately so you can hear the sound and confirm alerts are getting through before you rely on them.'),
      GuideDetail(3, 'Choose what alerts you',
          'Mute a whole category — fees, classes or announcements — and keep the rest. A muted category never alerts, though the messages still appear on the Notifications screen.'),
      GuideDetail(4, 'Quiet hours',
          'Silence alerts overnight between the hours you set. Nothing is lost: anything that arrives during the quiet window alerts you once it ends.'),
    ],
    tips: [
      'If alerts are blocked at the phone level, a warning appears at the top of this screen with a shortcut to your system settings.',
      'Using the app in a web browser? Sound only works after you have clicked the page once — every browser requires that before it will play audio.',
    ],
  ),
  GuideStep(
    key: 'profile',
    shot: 'assets/guide/student-details.png',
    icon: AppIcons.account_circle,
    title: 'Profile and Virtual ID',
    intro:
        'Your membership card, your details, and the switches for how the app looks and who you are viewing.',
    details: [
      GuideDetail(1, 'Virtual ID',
          'Your personal member QR with your name, grade and registration number. Show it at the counter to identify yourself or claim member offers.'),
      GuideDetail(2, 'Switch student or club',
          'Parents with several children, and members of more than one academy, switch between them here. The whole app follows your selection.'),
      GuideDetail(3, 'Personal info',
          'Your contact details as the club holds them. Use the pencil at the top to update them and change your photo.'),
      GuideDetail(4, 'Appearance and sign-out',
          'Further down are the light and dark mode switch, this guide, and Logout.'),
    ],
    note:
        'The Virtual ID QR identifies you. It is not the check-in code — attendance is only recorded by scanning your centre\'s poster.',
  ),
  GuideStep(
    key: 'chat',
    shot: 'assets/guide/chat.png',
    icon: AppIcons.forum,
    title: 'Chat and Help Desk',
    intro:
        'Chat Academy is the two-way channel to your club: their announcements to you, and your questions back to them.',
    details: [
      GuideDetail(1, 'Help Desk',
          'The pinned conversation at the top. Use it to start a new question with the club admin about anything — fees, schedules, membership.'),
      GuideDetail(2, 'Your conversations',
          'Every message the club has sent, newest first, as a thread you can open and read in full.'),
      GuideDetail(3, 'Replying',
          'Open a thread and send your answer. It reaches the academy\'s admin panel, and they follow up from there.'),
    ],
    tips: [
      'Replies land with the club\'s staff rather than an automated system, so expect a response in their office hours.',
    ],
  ),
  GuideStep(
    key: 'everything',
    shot: 'assets/guide/more.png',
    icon: AppIcons.grid_view,
    title: 'Finding everything else',
    intro:
        'More — the last tile in Quick Access — is the full catalogue of every screen in the app, grouped by what it is for.',
    details: [
      GuideDetail(1, 'Training',
          'Your trainer, today\'s classes, the timetable, attendance, booking and the QR scanner.'),
      GuideDetail(2, 'Payments',
          'Fees due, payment history, outstanding invoices, purchase requests and your past purchases.'),
      GuideDetail(3, 'Progress and club',
          'Your progress report and belt / rank, plus events, tournaments, offers, chat and the help desk.'),
      GuideDetail(4, 'Account',
          'Profile, student details, edit profile, notification settings and this guide.'),
    ],
    tips: [
      'Instructors get a different set of tabs — Collections, Reports and Settings in place of Schedule, Payments and Profile — but sign-in, QR check-in and notifications work exactly as described here.',
    ],
  ),
];
